# Shock2 AI System Configuration
system:
  name: "Shock2 AI"
  version: "2.0.0"
  debug: false
  log_level: "INFO"

database:
  type: "sqlite"
  path: "data/databases/shock2.db"

ai:
  model_cache_dir: "data/models"
  default_model: "gpt-3.5-turbo"
  max_tokens: 2048
  temperature: 0.7

voice:
  enabled: true
  engine: "pyttsx3"
  rate: 200
  volume: 0.9
  voice_id: 0

speech_recognition:
  engine: "whisper"
  model: "base"
  language: "en"

generation:
  output_dir: "output/generated"
  max_length: 1000

logging:
  log_dir: "logs"
  max_log_size: "10MB"
  backup_count: 5

data_sources:
  - "https://rss.cnn.com/rss/edition.rss"
  - "https://feeds.bbci.co.uk/news/rss.xml"
  - "https://rss.reuters.com/reuters/topNews"
